tumortest:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: tumor
    username: root
    password: 123456

  alioss:
    endPoint: oss-rg-china-mainland.aliyuncs.com
    accessKeyId:  LTAI5t7ugDmg5aAZwGK4agR5
    accessKeySecret:  mRgyJGHvupgAltu5RL8d93SEyfh5M3
    bucketName: tumor-pictrue

  redis:
    host: 192.168.189.128
    prot: 6379

  python:
    resultPath: C://Users/Administrator/Desktop/Tumor/TumorTesting/model/seg/
    imgPath: C://Users/Administrator/Desktop/Tumor/TumorTesting/model/outimg/
    startPath: C://Users//Administrator//Desktop//Tumor//TumorTesting//model//showImg.py