server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${tumortest.datasource.driver-class-name}
      url: jdbc:mysql://${tumortest.datasource.host}:${tumortest.datasource.port}/${tumortest.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${tumortest.datasource.username}
      password: ${tumortest.datasource.password}
  redis:
    host: ${tumortest.redis.host}
    port: ${tumortest.redis.prot}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tumorTest.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.tumorTest.entity
  #扫描mapper文件
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com:
      tumorTest:
        mapper: debug
        service: info
        controller: info

tumortest:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

  python:
    resultPath: ${tumortest.python.resultPath}
    imgPath: ${tumortest.python.imgPath}
    startPath: ${tumortest.python.startPath}

